server:
  port: 8080

spring:
  application:
    name: demo
  redis:
    host: 127.0.0.1
    port: 6379
    password: Shenxy198097
    lettuce:
      pool:
        max-active: 8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Shenxy198097
